package org.tomac.protocol.fix.messaging;

// DO NOT EDIT!!!
// This file is generated by FixMessageGenerator.
// If you need additional functionality, put it in a helper class
// that does not live in this folder!!!  Any java file in this folder 
// will be deleted upon the next run of the FixMessageGenerator!

import org.tomac.protocol.fix.messaging.FixTags;

import org.tomac.protocol.fix.FixUtils;

public class FixTags {

	public static final int PEGDIFFERENCE_INT = 211;
	public static final byte[]  PEGDIFFERENCE = "211".getBytes();

	public static final int EXECTRANSTYPE_INT = 20;
	public static final byte[]  EXECTRANSTYPE = "20".getBytes();

	public static final int HANDLINST_INT = 21;
	public static final byte[]  HANDLINST = "21".getBytes();

	public static final int TRDRPTSTATUS_INT = 939;
	public static final byte[]  TRDRPTSTATUS = "939".getBytes();
		public static final int TRDRPTSTATUS_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int BEGINSTRING_INT = 8;
	public static final byte[]  BEGINSTRING = "8".getBytes();
		public static final int BEGINSTRING_LENGTH = 7;

	public static final int TRADEREPORTID_INT = 571;
	public static final byte[]  TRADEREPORTID = "571".getBytes();
		public static final int TRADEREPORTID_LENGTH = 20;

	public static final int MEMO_INT = 5149;
	public static final byte[]  MEMO = "5149".getBytes();
		public static final int MEMO_LENGTH = 10;

	public static final int ORIGSENDINGTIME_INT = 122;
	public static final byte[]  ORIGSENDINGTIME = "122".getBytes();
		public static final int ORIGSENDINGTIME_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int GAPFILLFLAG_INT = 123;
	public static final byte[]  GAPFILLFLAG = "123".getBytes();

	public static final int EXPIRETIME_INT = 126;
	public static final byte[]  EXPIRETIME = "126".getBytes();
		public static final int EXPIRETIME_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int CLEARINGPRICE_INT = 9822;
	public static final byte[]  CLEARINGPRICE = "9822".getBytes();

	public static final int DELIVERTOCOMPID_INT = 128;
	public static final byte[]  DELIVERTOCOMPID = "128".getBytes();
		public static final int DELIVERTOCOMPID_LENGTH = 12;

	public static final int DELIVERTOSUBID_INT = 129;
	public static final byte[]  DELIVERTOSUBID = "129".getBytes();
		public static final int DELIVERTOSUBID_LENGTH = 6;

	public static final int DISSEMINATIONTIME_INT = 6169;
	public static final byte[]  DISSEMINATIONTIME = "6169".getBytes();
		public static final int DISSEMINATIONTIME_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int TIMEINFORCE_INT = 59;
	public static final byte[]  TIMEINFORCE = "59".getBytes();

	public static final int TEXT_INT = 58;
	public static final byte[]  TEXT = "58".getBytes();
		public static final int TEXT_LENGTH = FixUtils.FIX_MAX_STRING_TEXT_LENGTH;

	public static final int SYMBOL_INT = 55;
	public static final byte[]  SYMBOL = "55".getBytes();
		public static final int SYMBOL_LENGTH = 8;

	public static final int SIDE_INT = 54;
	public static final byte[]  SIDE = "54".getBytes();

	public static final int TARGETSUBID_INT = 57;
	public static final byte[]  TARGETSUBID = "57".getBytes();
		public static final int TARGETSUBID_LENGTH = 20;

	public static final int TARGETCOMPID_INT = 56;
	public static final byte[]  TARGETCOMPID = "56".getBytes();
		public static final int TARGETCOMPID_LENGTH = 12;

	public static final int SENDERSUBID_INT = 50;
	public static final byte[]  SENDERSUBID = "50".getBytes();
		public static final int SENDERSUBID_LENGTH = 6;

	public static final int SENDINGTIME_INT = 52;
	public static final byte[]  SENDINGTIME = "52".getBytes();
		public static final int SENDINGTIME_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int EXECRESTATEMENTREASON_INT = 378;
	public static final byte[]  EXECRESTATEMENTREASON = "378".getBytes();

	public static final int TRADETYPE_INT = 828;
	public static final byte[]  TRADETYPE = "828".getBytes();
		public static final int TRADETYPE_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int REFTAGID_INT = 371;
	public static final byte[]  REFTAGID = "371".getBytes();

	public static final int SESSIONREJECTREASON_INT = 373;
	public static final byte[]  SESSIONREJECTREASON = "373".getBytes();

	public static final int REFMSGTYPE_INT = 372;
	public static final byte[]  REFMSGTYPE = "372".getBytes();
		public static final int REFMSGTYPE_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int CONTRABROKER_INT = 375;
	public static final byte[]  CONTRABROKER = "375".getBytes();
		public static final int CONTRABROKER_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int SECONDARYORDERID_INT = 198;
	public static final byte[]  SECONDARYORDERID = "198".getBytes();
		public static final int SECONDARYORDERID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int REVERSALINDICATOR_INT = 700;
	public static final byte[]  REVERSALINDICATOR = "700".getBytes();
		public static final int REVERSALINDICATOR_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int ONBEHALFOFCOMPID_INT = 115;
	public static final byte[]  ONBEHALFOFCOMPID = "115".getBytes();
		public static final int ONBEHALFOFCOMPID_LENGTH = 12;

	public static final int ONBEHALFOFSUBID_INT = 116;
	public static final byte[]  ONBEHALFOFSUBID = "116".getBytes();
		public static final int ONBEHALFOFSUBID_LENGTH = 6;

	public static final int OVERRIDEFLAG_INT = 9854;
	public static final byte[]  OVERRIDEFLAG = "9854".getBytes();

	public static final int MINQTY_INT = 110;
	public static final byte[]  MINQTY = "110".getBytes();

	public static final int BREAKINDICATOR_INT = 9856;
	public static final byte[]  BREAKINDICATOR = "9856".getBytes();

	public static final int TESTREQID_INT = 112;
	public static final byte[]  TESTREQID = "112".getBytes();
		public static final int TESTREQID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int DISPLAYINST_INT = 9140;
	public static final byte[]  DISPLAYINST = "9140".getBytes();

	public static final int PROCESSCODE_INT = 81;
	public static final byte[]  PROCESSCODE = "81".getBytes();

	public static final int BEGINSEQNO_INT = 7;
	public static final byte[]  BEGINSEQNO = "7".getBytes();

	public static final int PRICETYPE_INT = 423;
	public static final byte[]  PRICETYPE = "423".getBytes();

	public static final int ORDERCAPACITY_INT = 528;
	public static final byte[]  ORDERCAPACITY = "528".getBytes();
		public static final int ORDERCAPACITY_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int ORDERRESTRICTIONS_INT = 529;
	public static final byte[]  ORDERRESTRICTIONS = "529".getBytes();
		public static final int ORDERRESTRICTIONS_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int CLEARINGACCOUNT_INT = 440;
	public static final byte[]  CLEARINGACCOUNT = "440".getBytes();
		public static final int CLEARINGACCOUNT_LENGTH = 12;

	public static final int HEARTBTINT_INT = 108;
	public static final byte[]  HEARTBTINT = "108".getBytes();

	public static final int CLIENTID_INT = 109;
	public static final byte[]  CLIENTID = "109".getBytes();
		public static final int CLIENTID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int LOCKEDINSTATUS_INT = 9847;
	public static final byte[]  LOCKEDINSTATUS = "9847".getBytes();

	public static final int DISCRETIONINST_INT = 388;
	public static final byte[]  DISCRETIONINST = "388".getBytes();

	public static final int DISCRETIONOFFSET_INT = 389;
	public static final byte[]  DISCRETIONOFFSET = "389".getBytes();

	public static final int SECURITYDESC_INT = 107;
	public static final byte[]  SECURITYDESC = "107".getBytes();
		public static final int SECURITYDESC_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int ORDSTATUS_INT = 39;
	public static final byte[]  ORDSTATUS = "39".getBytes();

	public static final int ORDERQTY_INT = 38;
	public static final byte[]  ORDERQTY = "38".getBytes();

	public static final int LASTSHARES_INT = 32;
	public static final byte[]  LASTSHARES = "32".getBytes();

	public static final int LASTPX_INT = 31;
	public static final byte[]  LASTPX = "31".getBytes();

	public static final int ORDERID_INT = 37;
	public static final byte[]  ORDERID = "37".getBytes();
		public static final int ORDERID_LENGTH = 32;

	public static final int NOCONTRABROKERS_INT = 382;
	public static final byte[]  NOCONTRABROKERS = "382".getBytes();

	public static final int MSGTYPE_INT = 35;
	public static final byte[]  MSGTYPE = "35".getBytes();
		public static final int MSGTYPE_LENGTH = 2;

	public static final int MSGSEQNUM_INT = 34;
	public static final byte[]  MSGSEQNUM = "34".getBytes();

	public static final int CLEARINGFIRM_INT = 439;
	public static final byte[]  CLEARINGFIRM = "439".getBytes();
		public static final int CLEARINGFIRM_LENGTH = 4;

	public static final int CXLREJRESPONSETO_INT = 434;
	public static final byte[]  CXLREJRESPONSETO = "434".getBytes();

	public static final int TRADEID_INT = 1003;
	public static final byte[]  TRADEID = "1003".getBytes();
		public static final int TRADEID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int TRADEREPORTREFID_INT = 572;
	public static final byte[]  TRADEREPORTREFID = "572".getBytes();
		public static final int TRADEREPORTREFID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int PARTYROLE_INT = 452;
	public static final byte[]  PARTYROLE = "452".getBytes();
		public static final int PARTYROLE_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int CLEARINGINSTRUCTION_INT = 577;
	public static final byte[]  CLEARINGINSTRUCTION = "577".getBytes();
		public static final int CLEARINGINSTRUCTION_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int TRANSACTTIME_INT = 60;
	public static final byte[]  TRANSACTTIME = "60".getBytes();
		public static final int TRANSACTTIME_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int CXLREJREASON_INT = 102;
	public static final byte[]  CXLREJREASON = "102".getBytes();

	public static final int FUTSETTDATE_INT = 64;
	public static final byte[]  FUTSETTDATE = "64".getBytes();
		public static final int FUTSETTDATE_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int ORDREJREASON_INT = 103;
	public static final byte[]  ORDREJREASON = "103".getBytes();

	public static final int SETTLBRKRCODE_INT = 174;
	public static final byte[]  SETTLBRKRCODE = "174".getBytes();
		public static final int SETTLBRKRCODE_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int TRADEREPORTTYPE_INT = 856;
	public static final byte[]  TRADEREPORTTYPE = "856".getBytes();
		public static final int TRADEREPORTTYPE_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int PUBLISHTRDINDICATOR_INT = 852;
	public static final byte[]  PUBLISHTRDINDICATOR = "852".getBytes();
		public static final int PUBLISHTRDINDICATOR_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int TIMESTAMPOWN_INT = 6204;
	public static final byte[]  TIMESTAMPOWN = "6204".getBytes();
		public static final int TIMESTAMPOWN_LENGTH = 20;

	public static final int TIMESTAMPCOUNTERPART_INT = 6205;
	public static final byte[]  TIMESTAMPCOUNTERPART = "6205".getBytes();
		public static final int TIMESTAMPCOUNTERPART_LENGTH = 20;

	public static final int INTERNALEXTERNAL_INT = 6206;
	public static final byte[]  INTERNALEXTERNAL = "6206".getBytes();

	public static final int AVGPX_INT = 6;
	public static final byte[]  AVGPX = "6".getBytes();

	public static final int CLREFID_INT = 6209;
	public static final byte[]  CLREFID = "6209".getBytes();
		public static final int CLREFID_LENGTH = 15;

	public static final int TRADEREPORTREJECTREASON_INT = 751;
	public static final byte[]  TRADEREPORTREJECTREASON = "751".getBytes();
		public static final int TRADEREPORTREJECTREASON_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int DELAYEDDISSEMINATIONINST_INT = 9855;
	public static final byte[]  DELAYEDDISSEMINATIONINST = "9855".getBytes();

	public static final int ENCRYPTMETHOD_INT = 98;
	public static final byte[]  ENCRYPTMETHOD = "98".getBytes();

	public static final int BRSEQNBR_INT = 9861;
	public static final byte[]  BRSEQNBR = "9861".getBytes();
		public static final int BRSEQNBR_LENGTH = 10;

	public static final int CONTRACLEARINGACCT_INT = 9863;
	public static final byte[]  CONTRACLEARINGACCT = "9863".getBytes();
		public static final int CONTRACLEARINGACCT_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int CONTRATRADEPA_INT = 9862;
	public static final byte[]  CONTRATRADEPA = "9862".getBytes();

	public static final int POSSRESEND_INT = 97;
	public static final byte[]  POSSRESEND = "97".getBytes();

	public static final int CLORDID_INT = 11;
	public static final byte[]  CLORDID = "11".getBytes();
		public static final int CLORDID_LENGTH = 20;

	public static final int CHECKSUM_INT = 10;
	public static final byte[]  CHECKSUM = "10".getBytes();
		public static final int CHECKSUM_LENGTH = 3;

	public static final int CURRENCY_INT = 15;
	public static final byte[]  CURRENCY = "15".getBytes();
		public static final int CURRENCY_LENGTH = FixUtils.CURRENCY_LENGTH;

	public static final int CUMQTY_INT = 14;
	public static final byte[]  CUMQTY = "14".getBytes();

	public static final int EXECID_INT = 17;
	public static final byte[]  EXECID = "17".getBytes();
		public static final int EXECID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int ENDSEQNO_INT = 16;
	public static final byte[]  ENDSEQNO = "16".getBytes();

	public static final int EXECREFID_INT = 19;
	public static final byte[]  EXECREFID = "19".getBytes();
		public static final int EXECREFID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int EXECINST_INT = 18;
	public static final byte[]  EXECINST = "18".getBytes();
		public static final int EXECINST_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int MAXFLOOR_INT = 111;
	public static final byte[]  MAXFLOOR = "111".getBytes();

	public static final int SUBMKTID_INT = 5815;
	public static final byte[]  SUBMKTID = "5815".getBytes();
		public static final int SUBMKTID_LENGTH = 3;

	public static final int CONTRAORDERRESTRICTIONS_INT = 5817;
	public static final byte[]  CONTRAORDERRESTRICTIONS = "5817".getBytes();

	public static final int LEAVESQTY_INT = 151;
	public static final byte[]  LEAVESQTY = "151".getBytes();

	public static final int EXECTYPE_INT = 150;
	public static final byte[]  EXECTYPE = "150".getBytes();

	public static final int SECONDARYTRADEREPORTREFID_INT = 881;
	public static final byte[]  SECONDARYTRADEREPORTREFID = "881".getBytes();
		public static final int SECONDARYTRADEREPORTREFID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int TRDMATCHID_INT = 880;
	public static final byte[]  TRDMATCHID = "880".getBytes();
		public static final int TRDMATCHID_LENGTH = 10;

	public static final int LOCKEDIN_INT = 9857;
	public static final byte[]  LOCKEDIN = "9857".getBytes();

	public static final int NEWSEQNO_INT = 36;
	public static final byte[]  NEWSEQNO = "36".getBytes();

	public static final int SECURITYID_INT = 48;
	public static final byte[]  SECURITYID = "48".getBytes();
		public static final int SECURITYID_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int SENDERCOMPID_INT = 49;
	public static final byte[]  SENDERCOMPID = "49".getBytes();
		public static final int SENDERCOMPID_LENGTH = 12;

	public static final int PRICE_INT = 44;
	public static final byte[]  PRICE = "44".getBytes();

	public static final int REFSEQNUM_INT = 45;
	public static final byte[]  REFSEQNUM = "45".getBytes();

	public static final int POSSDUPFLAG_INT = 43;
	public static final byte[]  POSSDUPFLAG = "43".getBytes();

	public static final int ORDTYPE_INT = 40;
	public static final byte[]  ORDTYPE = "40".getBytes();

	public static final int ORIGCLORDID_INT = 41;
	public static final byte[]  ORIGCLORDID = "41".getBytes();
		public static final int ORIGCLORDID_LENGTH = 20;

	public static final int BODYLENGTH_INT = 9;
	public static final byte[]  BODYLENGTH = "9".getBytes();
		public static final int BODYLENGTH_LENGTH = 3;

	public static final int CROSSTRADEFLAG_INT = 9355;
	public static final byte[]  CROSSTRADEFLAG = "9355".getBytes();

	public static final int RESETSEQNUMFLAG_INT = 141;
	public static final byte[]  RESETSEQNUMFLAG = "141".getBytes();

	public static final int EXECBROKER_INT = 76;
	public static final byte[]  EXECBROKER = "76".getBytes();
		public static final int EXECBROKER_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int TRADEDATE_INT = 75;
	public static final byte[]  TRADEDATE = "75".getBytes();
		public static final int TRADEDATE_LENGTH = FixUtils.UTCTIMESTAMP_LENGTH;

	public static final int TRANSBKDTIME_INT = 483;
	public static final byte[]  TRANSBKDTIME = "483".getBytes();
		public static final int TRANSBKDTIME_LENGTH = FixUtils.FIX_MAX_STRING_LENGTH;

	public static final int MICCODE_INT = 9292;
	public static final byte[]  MICCODE = "9292".getBytes();
		public static final int MICCODE_LENGTH = 4;

	public static final int LIQUIDITYFLAG_INT = 9882;
	public static final byte[]  LIQUIDITYFLAG = "9882".getBytes();

}
