package org.tomac.protocol.fix.messaging.fix50sp2.component;

// DO NOT EDIT!!!
// This file is generated by FixMessageGenerator.
// If you need additional functionality, put it in a helper class
// that does not live in this folder!!!  Any java file in this folder 
// will be deleted upon the next run of the FixMessageGenerator!

import java.nio.ByteBuffer;

import org.tomac.protocol.fix.FixUtils;
import org.tomac.protocol.fix.FixSessionException;
import org.tomac.protocol.fix.FixGarbledException;
import org.tomac.utils.Utils;
import org.tomac.protocol.fix.FixConstants;


import org.tomac.protocol.fix.messaging.fix50sp2.FixMessageInfo.SessionRejectReason;
import org.tomac.protocol.fix.messaging.fix50sp2.FixMessageInfo;
import org.tomac.protocol.fix.messaging.fix50sp2.FixTags;
import org.tomac.protocol.fix.messaging.fix50sp2.component.FixDerivativeInstrumentPartySubIDsGrp;

public class FixDerivativeInstrumentParties
{

	public int noDerivativeInstrumentParties;
	public DerivativeInstrumentParties[] group;

	public void getAll(int noDerivativeInstrumentParties, ByteBuffer buf) throws FixSessionException, FixGarbledException {
		this.noDerivativeInstrumentParties = noDerivativeInstrumentParties;

		if (noDerivativeInstrumentParties < 1) throw new FixSessionException(SessionRejectReason.INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP, ("Incorrect num in group count " + noDerivativeInstrumentParties ).getBytes(), FixTags.NODERIVATIVEINSTRUMENTPARTIES_INT, new byte[0]);
		// this will leak memory if we grow the group
		if (group == null || group.length < noDerivativeInstrumentParties) {
			group = new DerivativeInstrumentParties[noDerivativeInstrumentParties];

			for ( int i = 0; i < noDerivativeInstrumentParties; i++ ) group[i] = new DerivativeInstrumentParties();
	}

		for ( int i = 0; i < noDerivativeInstrumentParties; i++ ) 
			group[i].getAllGroup(buf);
	}

	public void clear() {
		for (int i = 0; i<noDerivativeInstrumentParties; i++)
			group[i].clear();
	}
	public void encode(ByteBuffer out) {
		for (int i = 0; i<noDerivativeInstrumentParties; i++)
			group[i].encode(out);
	}
	public boolean isSet() {
		for (int i = 0; i<noDerivativeInstrumentParties; i++)
			if (group[i].isSet()) return true;
		return false;
	}

	@Override
	public String toString() {
		String s = "";
		for (int i = 0; i<noDerivativeInstrumentParties; i++)
			s += group[i].toString();
		return s;
	}

public class DerivativeInstrumentParties implements FixComponent
{

	public byte[] derivativeInstrumentPartyID;
	public byte[] derivativeInstrumentPartyIDSource;
	public long derivativeInstrumentPartyRole = 0;
	public FixDerivativeInstrumentPartySubIDsGrp derivativeInstrumentPartySubIDsGrp;

	public DerivativeInstrumentParties() {
		super();

		derivativeInstrumentPartyID = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		derivativeInstrumentPartyIDSource = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		derivativeInstrumentPartySubIDsGrp = new FixDerivativeInstrumentPartySubIDsGrp();
		this.clear();

	}

	@Override
	public void clear()
	{

		// clear out all the fields that aren't msgType

		Utils.fill( derivativeInstrumentPartyID, (byte)0 );
		Utils.fill( derivativeInstrumentPartyIDSource, (byte)0 );
		derivativeInstrumentPartyRole = Long.MAX_VALUE;		
		derivativeInstrumentPartySubIDsGrp.clear();
	}

	public void getAllGroup(ByteBuffer buf) throws FixSessionException, FixGarbledException
	{

		int startTagPosition = buf.position();

		int id = FixUtils.getTagId( buf );
		int lastTagPosition = buf.position();
			ByteBuffer value;

			value = buf;

			if(id == FixTags.DERIVATIVEINSTRUMENTPARTYID_INT) {
				derivativeInstrumentPartyID = FixUtils.getTagStringValue(value, derivativeInstrumentPartyID);
				lastTagPosition = buf.position();

				id = FixUtils.getTagId( buf );
			}

			if(id == FixTags.DERIVATIVEINSTRUMENTPARTYIDSOURCE_INT) {
				derivativeInstrumentPartyIDSource = FixUtils.getTagStringValue(value, derivativeInstrumentPartyIDSource);
				lastTagPosition = buf.position();

				id = FixUtils.getTagId( buf );
			}

			if(id == FixTags.DERIVATIVEINSTRUMENTPARTYROLE_INT) {
				derivativeInstrumentPartyRole = FixUtils.getTagIntValue( value );
				lastTagPosition = buf.position();

				id = FixUtils.getTagId( buf );
			}

			if(id == FixTags.NODERIVATIVEINSTRUMENTPARTYSUBIDS_INT) {
				derivativeInstrumentPartySubIDsGrp.getAll(FixTags.NODERIVATIVEINSTRUMENTPARTYSUBIDS_INT, buf);
				lastTagPosition = buf.position();

				id = FixUtils.getTagId( buf );
			}

			id = checkRequiredTags();
				if (id > 0) throw new FixSessionException(SessionRejectReason.REQUIRED_TAG_MISSING, "Required tag missing".getBytes(), id, new byte[0] );

			buf.position( lastTagPosition );
			return;

	}

	private int checkRequiredTags() {
		int tag = -1;

		return tag;

	}
	@Override
	public boolean isSet()
	{
		if (FixUtils.isSet(derivativeInstrumentPartyID)) return true;
		if (FixUtils.isSet(derivativeInstrumentPartyIDSource)) return true;
		if (FixUtils.isSet(derivativeInstrumentPartyRole)) return true;
		if (FixUtils.isSet(derivativeInstrumentPartySubIDsGrp.noDerivativeInstrumentPartySubIDs)) return true;
		return false;
	}
	@Override
	public void encode( ByteBuffer out )
	{
		if (FixUtils.isSet(derivativeInstrumentPartyID)) FixUtils.putFixTag( out, FixTags.DERIVATIVEINSTRUMENTPARTYID_INT, derivativeInstrumentPartyID, 0, Utils.lastIndexTrim(derivativeInstrumentPartyID, (byte)0) );
		if (FixUtils.isSet(derivativeInstrumentPartyIDSource)) FixUtils.putFixTag( out, FixTags.DERIVATIVEINSTRUMENTPARTYIDSOURCE_INT, derivativeInstrumentPartyIDSource, 0, Utils.lastIndexTrim(derivativeInstrumentPartyIDSource, (byte)0) );
		if (FixUtils.isSet(derivativeInstrumentPartyRole)) FixUtils.putFixTag( out, FixTags.DERIVATIVEINSTRUMENTPARTYROLE_INT, derivativeInstrumentPartyRole);
		if (FixUtils.isSet(derivativeInstrumentPartySubIDsGrp.noDerivativeInstrumentPartySubIDs)) derivativeInstrumentPartySubIDsGrp.encode( out );
	}
	/**
	 * If you use toString for any other purpose than administrative printout.
	 * You will end up in nifelheim!
	**/
	@Override
	public String toString() {
		char sep = '\n';
		if (Boolean.getBoolean("fix.useOneLiner")) sep = ( byte )0x01;

		String s = "";

			if (FixUtils.isSet(derivativeInstrumentPartyID)) s += "DerivativeInstrumentPartyID(1293)=" + new String(derivativeInstrumentPartyID) + sep;
			if (FixUtils.isSet(derivativeInstrumentPartyIDSource)) s += "DerivativeInstrumentPartyIDSource(1294)=" + new String(derivativeInstrumentPartyIDSource) + sep;
			if (FixUtils.isSet(derivativeInstrumentPartyRole)) s += "DerivativeInstrumentPartyRole(1295)=" + String.valueOf(derivativeInstrumentPartyRole) + sep;
			if (FixUtils.isSet(derivativeInstrumentPartySubIDsGrp.noDerivativeInstrumentPartySubIDs)) s += derivativeInstrumentPartySubIDsGrp.toString();
		return s;

	}

	@Override
	public boolean equals(Object o) {
		if (! ( o instanceof DerivativeInstrumentParties)) return false;

			DerivativeInstrumentParties msg = (DerivativeInstrumentParties) o;

		if ( ! super.equals(msg) ) return false;

		if (!Utils.equals( derivativeInstrumentPartyID, msg.derivativeInstrumentPartyID)) return false;

		if (!Utils.equals( derivativeInstrumentPartyIDSource, msg.derivativeInstrumentPartyIDSource)) return false;

		if (!( derivativeInstrumentPartyRole==msg.derivativeInstrumentPartyRole)) return false;

		if (!derivativeInstrumentPartySubIDsGrp.equals(msg.derivativeInstrumentPartySubIDsGrp)) return false;

		return true;
	}
}
}
