package org.tomac.protocol.fix.messaging.fix50sp2.component;

// DO NOT EDIT!!!
// This file is generated by FixMessageGenerator.
// If you need additional functionality, put it in a helper class
// that does not live in this folder!!!  Any java file in this folder 
// will be deleted upon the next run of the FixMessageGenerator!

import java.nio.ByteBuffer;

import org.tomac.protocol.fix.FixUtils;
import org.tomac.protocol.fix.FixSessionException;
import org.tomac.protocol.fix.FixGarbledException;
import org.tomac.utils.Utils;
import org.tomac.protocol.fix.FixConstants;


import org.tomac.protocol.fix.messaging.fix50sp2.FixMessageInfo.SessionRejectReason;
import org.tomac.protocol.fix.messaging.fix50sp2.FixMessageInfo;
import org.tomac.protocol.fix.messaging.fix50sp2.FixTags;

public class FixSettlPtysSubGrp
{

	public int noSettlPartySubIDs;
	public SettlPtysSubGrp[] group;

	public void getAll(int noSettlPartySubIDs, ByteBuffer buf) throws FixSessionException, FixGarbledException {
		this.noSettlPartySubIDs = noSettlPartySubIDs;

		if (noSettlPartySubIDs < 1) throw new FixSessionException(SessionRejectReason.INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP, ("Incorrect num in group count " + noSettlPartySubIDs ).getBytes(), FixTags.NOSETTLPARTYSUBIDS_INT, new byte[0]);
		// this will leak memory if we grow the group
		if (group == null || group.length < noSettlPartySubIDs) {
			group = new SettlPtysSubGrp[noSettlPartySubIDs];

			for ( int i = 0; i < noSettlPartySubIDs; i++ ) group[i] = new SettlPtysSubGrp();
	}

		for ( int i = 0; i < noSettlPartySubIDs; i++ ) 
			group[i].getAllGroup(buf);
	}

	public void clear() {
		for (int i = 0; i<noSettlPartySubIDs; i++)
			group[i].clear();
	}
	public void encode(ByteBuffer out) {
		for (int i = 0; i<noSettlPartySubIDs; i++)
			group[i].encode(out);
	}
	public boolean isSet() {
		for (int i = 0; i<noSettlPartySubIDs; i++)
			if (group[i].isSet()) return true;
		return false;
	}

	@Override
	public boolean equals(Object o) {
		if (! ( o instanceof FixSettlPtysSubGrp)) return false;

		FixSettlPtysSubGrp msg = (FixSettlPtysSubGrp) o;

		for (int i = 0; i<noSettlPartySubIDs; i++)
			if (!group[i].equals(msg.group[i])) return false;
		return true;
	}

	@Override
	public String toString() {
		String s = "";
		for (int i = 0; i<noSettlPartySubIDs; i++)
			s += group[i].toString();
		return s;
	}

public class SettlPtysSubGrp implements FixComponent
{

	public byte[] settlPartySubID;
	public long settlPartySubIDType = 0;

	public SettlPtysSubGrp() {
		super();

		settlPartySubID = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		this.clear();

	}

	@Override
	public void clear()
	{

		// clear out all the fields that aren't msgType

		Utils.fill( settlPartySubID, (byte)0 );
		settlPartySubIDType = Long.MAX_VALUE;		
	}

	public void getAllGroup(ByteBuffer buf) throws FixSessionException, FixGarbledException
	{

		int startTagPosition = buf.position();

		int id = FixUtils.getTagId( buf );
		int lastTagPosition = buf.position();
			ByteBuffer value;

			value = buf;

			if(id == FixTags.SETTLPARTYSUBID_INT) {
				settlPartySubID = FixUtils.getTagStringValue(value, settlPartySubID);
				lastTagPosition = buf.position();

				id = FixUtils.getTagId( buf );
			}

			if(id == FixTags.SETTLPARTYSUBIDTYPE_INT) {
				settlPartySubIDType = FixUtils.getTagIntValue( value );
				lastTagPosition = buf.position();

				id = FixUtils.getTagId( buf );
			}

			id = checkRequiredTags();
				if (id > 0) throw new FixSessionException(SessionRejectReason.REQUIRED_TAG_MISSING, "Required tag missing".getBytes(), id, new byte[0] );

			buf.position( lastTagPosition );
			return;

	}

	private int checkRequiredTags() {
		int tag = -1;

		return tag;

	}
	@Override
	public boolean isSet()
	{
		if (FixUtils.isSet(settlPartySubID)) return true;
		if (FixUtils.isSet(settlPartySubIDType)) return true;
		return false;
	}
	@Override
	public void encode( ByteBuffer out )
	{
		if (FixUtils.isSet(settlPartySubID)) FixUtils.putFixTag( out, FixTags.SETTLPARTYSUBID_INT, settlPartySubID, 0, Utils.lastIndexTrim(settlPartySubID, (byte)0) );
		if (FixUtils.isSet(settlPartySubIDType)) FixUtils.putFixTag( out, FixTags.SETTLPARTYSUBIDTYPE_INT, settlPartySubIDType);
	}
	/**
	 * If you use toString for any other purpose than administrative printout.
	 * You will end up in nifelheim!
	**/
	@Override
	public String toString() {
		char sep = '\n';
		if (Boolean.getBoolean("fix.useOneLiner")) sep = ( byte )0x01;

		String s = "";

			if (FixUtils.isSet(settlPartySubID)) s += "SettlPartySubID(785)=" + new String(settlPartySubID) + sep;
			if (FixUtils.isSet(settlPartySubIDType)) s += "SettlPartySubIDType(786)=" + String.valueOf(settlPartySubIDType) + sep;
		return s;

	}

	@Override
	public boolean equals(Object o) {
		if (! ( o instanceof SettlPtysSubGrp)) return false;

			SettlPtysSubGrp msg = (SettlPtysSubGrp) o;

		if (!Utils.equals( settlPartySubID, msg.settlPartySubID)) return false;

		if (!( settlPartySubIDType==msg.settlPartySubIDType)) return false;

		return true;
	}
}
}
