package org.tomac.protocol.fix.messaging.fix50sp2;

// DO NOT EDIT!!!
// This file is generated by FixMessageGenerator.
// If you need additional functionality, put it in a helper class
// that does not live in this folder!!!  Any java file in this folder 
// will be deleted upon the next run of the FixMessageGenerator!

import java.nio.ByteBuffer;

import org.tomac.protocol.fix.FixUtils;
import org.tomac.protocol.fix.FixSessionException;
import org.tomac.utils.Utils;
import org.tomac.protocol.fix.FixConstants;



public class FixUserRequest extends FixMessage
{

	public byte[] userRequestID;
	public long userRequestType = 0;
	public byte[] username;
	public byte[] password;
	public byte[] newPassword;
	public long encryptedPasswordMethod = 0;
	public long encryptedPasswordLen = 0;
	public byte[] encryptedPassword;
	public long encryptedNewPasswordLen = 0;
	public byte[] encryptedNewPassword;
	public long rawDataLength = 0;
	public byte[] rawData;

	public FixUserRequest() {
		super();

		userRequestID = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		username = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		password = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		newPassword = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		encryptedPassword = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		encryptedNewPassword = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		rawData = new byte[FixUtils.FIX_MAX_STRING_LENGTH];
		this.clear();

		msgType = MsgTypes.USERREQUEST_INT;

	}

	@Override
	public void clear()
	{

		// clear out all the fields that aren't msgType

		Utils.fill( userRequestID, (byte)0 );
		userRequestType = Long.MAX_VALUE;		
		Utils.fill( username, (byte)0 );
		Utils.fill( password, (byte)0 );
		Utils.fill( newPassword, (byte)0 );
		encryptedPasswordMethod = Long.MAX_VALUE;		
		encryptedPasswordLen = Long.MAX_VALUE;		
		Utils.fill( encryptedPassword, (byte)0 );
		encryptedNewPasswordLen = Long.MAX_VALUE;		
		Utils.fill( encryptedNewPassword, (byte)0 );
		rawDataLength = Long.MAX_VALUE;		
		Utils.fill( rawData, (byte)0 );
	}

	@Override
	public void getAll() throws FixSessionException, IllegalStateException
	{

		int startTagPosition = buf.position();

		super.getAll();

		// assumption message is full otherwise decode would return null
		// so negative id means that we are at the end of the message
		int id;
		int lastTagPosition = buf.position();
		while ( ( id = FixUtils.getTagId( buf ) ) > 0 )
		{
			ByteBuffer value;

			value = buf;

			switch( id ) {

			case FixTags.USERREQUESTID_INT:
				userRequestID = FixUtils.getTagStringValue(value, userRequestID);
				break;

			case FixTags.USERREQUESTTYPE_INT:
				userRequestType = FixUtils.getTagIntValue( value );
				if (!UserRequestType.isValid(userRequestType) ) throw new FixSessionException(buf, "Invalid enumerated value(" + userRequestType + ") for tag: " + id );
				break;

			case FixTags.USERNAME_INT:
				username = FixUtils.getTagStringValue(value, username);
				break;

			case FixTags.PASSWORD_INT:
				password = FixUtils.getTagStringValue(value, password);
				break;

			case FixTags.NEWPASSWORD_INT:
				newPassword = FixUtils.getTagStringValue(value, newPassword);
				break;

			case FixTags.ENCRYPTEDPASSWORDMETHOD_INT:
				encryptedPasswordMethod = FixUtils.getTagIntValue( value );
				break;

			case FixTags.ENCRYPTEDPASSWORDLEN_INT:
				encryptedPasswordLen = FixUtils.getTagIntValue( value );
				break;

			case FixTags.ENCRYPTEDPASSWORD_INT:
				encryptedPassword = FixUtils.getTagStringValue(value, encryptedPassword);
				break;

			case FixTags.ENCRYPTEDNEWPASSWORDLEN_INT:
				encryptedNewPasswordLen = FixUtils.getTagIntValue( value );
				break;

			case FixTags.ENCRYPTEDNEWPASSWORD_INT:
				encryptedNewPassword = FixUtils.getTagStringValue(value, encryptedNewPassword);
				break;

			case FixTags.RAWDATALENGTH_INT:
				rawDataLength = FixUtils.getTagIntValue( value );
				break;

			case FixTags.RAWDATA_INT:
				rawData = FixUtils.getTagStringValue(value, rawData);
				break;

			// for a message always get the checksum
			case FixTags.CHECKSUM_INT:
				checkSum = FixUtils.getTagIntValue( value );

				id = checkRequiredTags();
				if (id > 0) throw new FixSessionException(buf, "Required tag missing: " + id );

				return;

			default:
				throw new FixSessionException(buf, "Unknown tag: " + id );

			}

			lastTagPosition = buf.position();

		}

		buf.position(startTagPosition);

	}

	private int checkRequiredTags() {
		int tag = -1;

		if (! FixUtils.isSet(userRequestID) ) return FixTags.USERREQUESTID_INT;
		if (! FixUtils.isSet(userRequestType) ) return FixTags.USERREQUESTTYPE_INT;
		if (! FixUtils.isSet(username) ) return FixTags.USERNAME_INT;
		return tag;

	}
	@Override
	public void encode( ByteBuffer out )
	{
		// Encode message. Set msgSeqNum and sendingTime and optional resend flags, before encoding. 

		int msgStart = out.position();

		out.put( BEGINSTRING_VALUE_WITH_TAG );

		int msgLengthValueStart = out.position() + 2 /* 9= */;

		// placeholder
		FixUtils.putFixTag(out, FixTags.BODYLENGTH_INT, FixConstants.MAX_MESSAGE_SIZE );

		int msgTypeStart = out.position();

		FixUtils.putFixTag( out, FixTags.MSGTYPE_INT, MsgTypes.USERREQUEST);

		// encode all fields including the header

		if (FixUtils.isSet(applVerID)) FixUtils.putFixTag( out, FixTags.APPLVERID_INT, applVerID, 0, Utils.lastIndexTrim(applVerID, (byte)0) );
		if (FixUtils.isSet(cstmApplVerID)) FixUtils.putFixTag( out, FixTags.CSTMAPPLVERID_INT, cstmApplVerID, 0, Utils.lastIndexTrim(cstmApplVerID, (byte)0) );
		if (FixUtils.isSet(applExtID)) FixUtils.putFixTag( out, FixTags.APPLEXTID_INT, applExtID);
		FixUtils.putFixTag( out, FixTags.SENDERCOMPID_INT, senderCompID, 0, Utils.lastIndexTrim(senderCompID, (byte)0) );
		FixUtils.putFixTag( out, FixTags.TARGETCOMPID_INT, targetCompID, 0, Utils.lastIndexTrim(targetCompID, (byte)0) );
		if (FixUtils.isSet(onBehalfOfCompID)) FixUtils.putFixTag( out, FixTags.ONBEHALFOFCOMPID_INT, onBehalfOfCompID, 0, Utils.lastIndexTrim(onBehalfOfCompID, (byte)0) );
		if (FixUtils.isSet(deliverToCompID)) FixUtils.putFixTag( out, FixTags.DELIVERTOCOMPID_INT, deliverToCompID, 0, Utils.lastIndexTrim(deliverToCompID, (byte)0) );
		if (FixUtils.isSet(secureDataLen)) FixUtils.putFixTag( out, FixTags.SECUREDATALEN_INT, secureDataLen);
		if (FixUtils.isSet(secureData)) FixUtils.putFixTag( out, FixTags.SECUREDATA_INT, secureData, 0, Utils.lastIndexTrim(secureData, (byte)0) );
		FixUtils.putFixTag( out, FixTags.MSGSEQNUM_INT, msgSeqNum);
		if (FixUtils.isSet(senderSubID)) FixUtils.putFixTag( out, FixTags.SENDERSUBID_INT, senderSubID, 0, Utils.lastIndexTrim(senderSubID, (byte)0) );
		if (FixUtils.isSet(senderLocationID)) FixUtils.putFixTag( out, FixTags.SENDERLOCATIONID_INT, senderLocationID, 0, Utils.lastIndexTrim(senderLocationID, (byte)0) );
		if (FixUtils.isSet(targetSubID)) FixUtils.putFixTag( out, FixTags.TARGETSUBID_INT, targetSubID, 0, Utils.lastIndexTrim(targetSubID, (byte)0) );
		if (FixUtils.isSet(targetLocationID)) FixUtils.putFixTag( out, FixTags.TARGETLOCATIONID_INT, targetLocationID, 0, Utils.lastIndexTrim(targetLocationID, (byte)0) );
		if (FixUtils.isSet(onBehalfOfSubID)) FixUtils.putFixTag( out, FixTags.ONBEHALFOFSUBID_INT, onBehalfOfSubID, 0, Utils.lastIndexTrim(onBehalfOfSubID, (byte)0) );
		if (FixUtils.isSet(onBehalfOfLocationID)) FixUtils.putFixTag( out, FixTags.ONBEHALFOFLOCATIONID_INT, onBehalfOfLocationID, 0, Utils.lastIndexTrim(onBehalfOfLocationID, (byte)0) );
		if (FixUtils.isSet(deliverToSubID)) FixUtils.putFixTag( out, FixTags.DELIVERTOSUBID_INT, deliverToSubID, 0, Utils.lastIndexTrim(deliverToSubID, (byte)0) );
		if (FixUtils.isSet(deliverToLocationID)) FixUtils.putFixTag( out, FixTags.DELIVERTOLOCATIONID_INT, deliverToLocationID, 0, Utils.lastIndexTrim(deliverToLocationID, (byte)0) );
		if (FixUtils.isSet(possDupFlag)) FixUtils.putFixTag( out, FixTags.POSSDUPFLAG_INT, possDupFlag?(byte)'Y':(byte)'N' );
		if (FixUtils.isSet(possResend)) FixUtils.putFixTag( out, FixTags.POSSRESEND_INT, possResend?(byte)'Y':(byte)'N' );
		FixUtils.putFixTag( out, FixTags.SENDINGTIME_INT, sendingTime);
		if (FixUtils.isSet(origSendingTime)) FixUtils.putFixTag( out, FixTags.ORIGSENDINGTIME_INT, origSendingTime);
		if (FixUtils.isSet(xmlDataLen)) FixUtils.putFixTag( out, FixTags.XMLDATALEN_INT, xmlDataLen);
		if (FixUtils.isSet(xmlData)) FixUtils.putFixTag( out, FixTags.XMLDATA_INT, xmlData, 0, Utils.lastIndexTrim(xmlData, (byte)0) );
		if (FixUtils.isSet(messageEncoding)) FixUtils.putFixTag( out, FixTags.MESSAGEENCODING_INT, messageEncoding, 0, Utils.lastIndexTrim(messageEncoding, (byte)0) );
		if (FixUtils.isSet(lastMsgSeqNumProcessed)) FixUtils.putFixTag( out, FixTags.LASTMSGSEQNUMPROCESSED_INT, lastMsgSeqNumProcessed);

		FixUtils.putFixTag( out, FixTags.USERREQUESTID_INT, userRequestID, 0, Utils.lastIndexTrim(userRequestID, (byte)0) );
		FixUtils.putFixTag( out, FixTags.USERREQUESTTYPE_INT, userRequestType);
		FixUtils.putFixTag( out, FixTags.USERNAME_INT, username, 0, Utils.lastIndexTrim(username, (byte)0) );
		if (FixUtils.isSet(password)) FixUtils.putFixTag( out, FixTags.PASSWORD_INT, password, 0, Utils.lastIndexTrim(password, (byte)0) );
		if (FixUtils.isSet(newPassword)) FixUtils.putFixTag( out, FixTags.NEWPASSWORD_INT, newPassword, 0, Utils.lastIndexTrim(newPassword, (byte)0) );
		if (FixUtils.isSet(encryptedPasswordMethod)) FixUtils.putFixTag( out, FixTags.ENCRYPTEDPASSWORDMETHOD_INT, encryptedPasswordMethod);
		if (FixUtils.isSet(encryptedPasswordLen)) FixUtils.putFixTag( out, FixTags.ENCRYPTEDPASSWORDLEN_INT, encryptedPasswordLen);
		if (FixUtils.isSet(encryptedPassword)) FixUtils.putFixTag( out, FixTags.ENCRYPTEDPASSWORD_INT, encryptedPassword, 0, Utils.lastIndexTrim(encryptedPassword, (byte)0) );
		if (FixUtils.isSet(encryptedNewPasswordLen)) FixUtils.putFixTag( out, FixTags.ENCRYPTEDNEWPASSWORDLEN_INT, encryptedNewPasswordLen);
		if (FixUtils.isSet(encryptedNewPassword)) FixUtils.putFixTag( out, FixTags.ENCRYPTEDNEWPASSWORD_INT, encryptedNewPassword, 0, Utils.lastIndexTrim(encryptedNewPassword, (byte)0) );
		if (FixUtils.isSet(rawDataLength)) FixUtils.putFixTag( out, FixTags.RAWDATALENGTH_INT, rawDataLength);
		if (FixUtils.isSet(rawData)) FixUtils.putFixTag( out, FixTags.RAWDATA_INT, rawData, 0, Utils.lastIndexTrim(rawData, (byte)0) );
		// the checksum at the end

		int checkSumStart = out.position();
		out.position( msgLengthValueStart );
		bodyLength = checkSumStart - msgTypeStart;
		Utils.longToNumeric( out, bodyLength, Utils.digits(FixConstants.MAX_MESSAGE_SIZE) );

		checkSum = FixUtils.computeChecksum( out, msgStart, checkSumStart );
		out.position( checkSumStart );
		FixUtils.putFixTag( out, FixTags.CHECKSUM_INT, checkSum );

		out.flip();

	}
	@Override		
	public void printBuffer(ByteBuffer out) {

		out.put(buf);

		out.flip();

	}

	/**
	 * If you use toString for any other purpose than administrative printout.
	 * You will end up in nifelheim!
	**/
	@Override
	public String toString() {
		char sep = '\n';
		if (Boolean.getBoolean("fix.useOneLiner")) sep = SOH;

		String s = "BeginString(8)=" + new String(BEGINSTRING_VALUE) + sep;
		s += "BodyLength(9)=" + bodyLength + sep;
		s += "MsgType(35)=" + new String(MsgTypes.USERREQUEST) + sep;

		try {
			// print all fields including the header

			if (FixUtils.isSet(applVerID)) s += "ApplVerID(1128)=" + new String(applVerID) + sep;
			if (FixUtils.isSet(cstmApplVerID)) s += "CstmApplVerID(1129)=" + new String(cstmApplVerID) + sep;
			if (FixUtils.isSet(applExtID)) s += "ApplExtID(1156)=" + String.valueOf(applExtID) + sep;
			 s += "SenderCompID(49)=" + new String(senderCompID) + sep;
			 s += "TargetCompID(56)=" + new String(targetCompID) + sep;
			if (FixUtils.isSet(onBehalfOfCompID)) s += "OnBehalfOfCompID(115)=" + new String(onBehalfOfCompID) + sep;
			if (FixUtils.isSet(deliverToCompID)) s += "DeliverToCompID(128)=" + new String(deliverToCompID) + sep;
			if (FixUtils.isSet(secureDataLen)) s += "SecureDataLen(90)=" + String.valueOf(secureDataLen) + sep;
			if (FixUtils.isSet(secureData)) s += "SecureData(91)=" + new String(secureData) + sep;
			 s += "MsgSeqNum(34)=" + String.valueOf(msgSeqNum) + sep;
			if (FixUtils.isSet(senderSubID)) s += "SenderSubID(50)=" + new String(senderSubID) + sep;
			if (FixUtils.isSet(senderLocationID)) s += "SenderLocationID(142)=" + new String(senderLocationID) + sep;
			if (FixUtils.isSet(targetSubID)) s += "TargetSubID(57)=" + new String(targetSubID) + sep;
			if (FixUtils.isSet(targetLocationID)) s += "TargetLocationID(143)=" + new String(targetLocationID) + sep;
			if (FixUtils.isSet(onBehalfOfSubID)) s += "OnBehalfOfSubID(116)=" + new String(onBehalfOfSubID) + sep;
			if (FixUtils.isSet(onBehalfOfLocationID)) s += "OnBehalfOfLocationID(144)=" + new String(onBehalfOfLocationID) + sep;
			if (FixUtils.isSet(deliverToSubID)) s += "DeliverToSubID(129)=" + new String(deliverToSubID) + sep;
			if (FixUtils.isSet(deliverToLocationID)) s += "DeliverToLocationID(145)=" + new String(deliverToLocationID) + sep;
			if (FixUtils.isSet(possDupFlag)) s += "PossDupFlag(43)=" + String.valueOf(possDupFlag) + sep;
			if (FixUtils.isSet(possResend)) s += "PossResend(97)=" + String.valueOf(possResend) + sep;
			 s += "SendingTime(52)=" + new String(sendingTime) + sep;
			if (FixUtils.isSet(origSendingTime)) s += "OrigSendingTime(122)=" + new String(origSendingTime) + sep;
			if (FixUtils.isSet(xmlDataLen)) s += "XmlDataLen(212)=" + String.valueOf(xmlDataLen) + sep;
			if (FixUtils.isSet(xmlData)) s += "XmlData(213)=" + new String(xmlData) + sep;
			if (FixUtils.isSet(messageEncoding)) s += "MessageEncoding(347)=" + new String(messageEncoding) + sep;
			if (FixUtils.isSet(lastMsgSeqNumProcessed)) s += "LastMsgSeqNumProcessed(369)=" + String.valueOf(lastMsgSeqNumProcessed) + sep;

			 s += "UserRequestID(923)=" + new String(userRequestID) + sep;
			 s += "UserRequestType(924)=" + String.valueOf(userRequestType) + sep;
			 s += "Username(553)=" + new String(username) + sep;
			if (FixUtils.isSet(password)) s += "Password(554)=" + new String(password) + sep;
			if (FixUtils.isSet(newPassword)) s += "NewPassword(925)=" + new String(newPassword) + sep;
			if (FixUtils.isSet(encryptedPasswordMethod)) s += "EncryptedPasswordMethod(1400)=" + String.valueOf(encryptedPasswordMethod) + sep;
			if (FixUtils.isSet(encryptedPasswordLen)) s += "EncryptedPasswordLen(1401)=" + String.valueOf(encryptedPasswordLen) + sep;
			if (FixUtils.isSet(encryptedPassword)) s += "EncryptedPassword(1402)=" + new String(encryptedPassword) + sep;
			if (FixUtils.isSet(encryptedNewPasswordLen)) s += "EncryptedNewPasswordLen(1403)=" + String.valueOf(encryptedNewPasswordLen) + sep;
			if (FixUtils.isSet(encryptedNewPassword)) s += "EncryptedNewPassword(1404)=" + new String(encryptedNewPassword) + sep;
			if (FixUtils.isSet(rawDataLength)) s += "RawDataLength(95)=" + String.valueOf(rawDataLength) + sep;
			if (FixUtils.isSet(rawData)) s += "RawData(96)=" + new String(rawData) + sep;

			s += "checkSum(10)=" + String.valueOf(checkSum) + sep;

		} catch(Exception e) {  };

		return s;
	}

	@Override
	public boolean equals(Object o) {
		if (! ( o instanceof FixUserRequest)) return false;

			FixUserRequest msg = (FixUserRequest) o;

		if ( ! super.equals(msg) ) return false;

		if (!Utils.equals( userRequestID, msg.userRequestID)) return false;

		if (!( userRequestType==msg.userRequestType)) return false;

		if (!Utils.equals( username, msg.username)) return false;

		if (!Utils.equals( password, msg.password)) return false;

		if (!Utils.equals( newPassword, msg.newPassword)) return false;

		if (!( encryptedPasswordMethod==msg.encryptedPasswordMethod)) return false;

		if (!( encryptedPasswordLen==msg.encryptedPasswordLen)) return false;

		if (!Utils.equals( encryptedPassword, msg.encryptedPassword)) return false;

		if (!( encryptedNewPasswordLen==msg.encryptedNewPasswordLen)) return false;

		if (!Utils.equals( encryptedNewPassword, msg.encryptedNewPassword)) return false;

		if (!( rawDataLength==msg.rawDataLength)) return false;

		if (!Utils.equals( rawData, msg.rawData)) return false;

		return true;
	}
}
