package org.tomac.protocol.fix.messaging.fix42nordic;

// DO NOT EDIT!!!
// This file is generated by FixMessageGenerator.
// If you need additional functionality, put it in a helper class
// that does not live in this folder!!!  Any java file in this folder 
// will be deleted upon the next run of the FixMessageGenerator!

import java.nio.ByteBuffer;
import org.tomac.protocol.fix.FixSessionException;
import org.tomac.protocol.fix.FixGarbledException;
import org.tomac.protocol.fix.FixUtils;
public class FixMessageParser implements FixMessageInfo
{

	public FixSessionValidator validator = new FixSessionValidator() {};

	FixAcceptedCancelReplace fixAcceptedCancelReplace = new FixAcceptedCancelReplace();
	FixAcceptedCancel fixAcceptedCancel = new FixAcceptedCancel();
	FixApplicationReject fixApplicationReject = new FixApplicationReject();
	FixBreakNotification fixBreakNotification = new FixBreakNotification();
	FixBusinessReject fixBusinessReject = new FixBusinessReject();
	FixCancelNotification fixCancelNotification = new FixCancelNotification();
	FixEntryNotificationtoAllegedFirm fixEntryNotificationtoAllegedFirm = new FixEntryNotificationtoAllegedFirm();
	FixExecutionReportFill fixExecutionReportFill = new FixExecutionReportFill();
	FixExecutionRestatement fixExecutionRestatement = new FixExecutionRestatement();
	FixLockedinNotification fixLockedinNotification = new FixLockedinNotification();
	FixLockedinTradeBreak fixLockedinTradeBreak = new FixLockedinTradeBreak();
	FixOrderAcknowledgement fixOrderAcknowledgement = new FixOrderAcknowledgement();
	FixOrderReject fixOrderReject = new FixOrderReject();
	FixPendingCancel fixPendingCancel = new FixPendingCancel();
	FixTradeEntryNotificationtoEnteringFirm fixTradeEntryNotificationtoEnteringFirm = new FixTradeEntryNotificationtoEnteringFirm();
	FixTradeReportCancel fixTradeReportCancel = new FixTradeReportCancel();
	FixTradeReportEntry fixTradeReportEntry = new FixTradeReportEntry();
	FixHeartbeat fixHeartbeat = new FixHeartbeat();
	FixLogon fixLogon = new FixLogon();
	FixLogout fixLogout = new FixLogout();
	FixOrderSingle fixOrderSingle = new FixOrderSingle();
	FixOrderCancelReject fixOrderCancelReject = new FixOrderCancelReject();
	FixRejectedCancelReplace fixRejectedCancelReplace = new FixRejectedCancelReplace();
	FixOrderCancelReplaceRequest fixOrderCancelReplaceRequest = new FixOrderCancelReplaceRequest();
	FixOrderCancelRequest fixOrderCancelRequest = new FixOrderCancelRequest();
	FixReject fixReject = new FixReject();
	FixResendRequest fixResendRequest = new FixResendRequest();
	FixSequenceReset fixSequenceReset = new FixSequenceReset();
	FixTestRequest fixTestRequest = new FixTestRequest();
	FixMessage fixMessage = new FixMessage() {
		@Override
		public void encode(ByteBuffer out) {}
		@Override
		public void printBuffer(ByteBuffer out) {}
		@Override
		public String toString() { return null; }
		};

	public void parse( ByteBuffer buf, FixMessageListener l) throws FixSessionException, FixGarbledException {

		int msgTypeInt = FixMessage.crackMsgType(buf);

		switch (msgTypeInt) {

			case MsgTypes.ACCEPTEDCANCELREPLACE_INT:
				fixAcceptedCancelReplace.setBuffer( buf );
				fixAcceptedCancelReplace.getAll();
				if (!validator.validate(fixAcceptedCancelReplace)) return;
				l.onFixAcceptedCancelReplace(fixAcceptedCancelReplace);
				break;
			case MsgTypes.ACCEPTEDCANCEL_INT:
				fixAcceptedCancel.setBuffer( buf );
				fixAcceptedCancel.getAll();
				if (!validator.validate(fixAcceptedCancel)) return;
				l.onFixAcceptedCancel(fixAcceptedCancel);
				break;
			case MsgTypes.APPLICATIONREJECT_INT:
				fixApplicationReject.setBuffer( buf );
				fixApplicationReject.getAll();
				if (!validator.validate(fixApplicationReject)) return;
				l.onFixApplicationReject(fixApplicationReject);
				break;
			case MsgTypes.BREAKNOTIFICATION_INT:
				fixBreakNotification.setBuffer( buf );
				fixBreakNotification.getAll();
				if (!validator.validate(fixBreakNotification)) return;
				l.onFixBreakNotification(fixBreakNotification);
				break;
			case MsgTypes.BUSINESSREJECT_INT:
				fixBusinessReject.setBuffer( buf );
				fixBusinessReject.getAll();
				if (!validator.validate(fixBusinessReject)) return;
				l.onFixBusinessReject(fixBusinessReject);
				break;
			case MsgTypes.CANCELNOTIFICATION_INT:
				fixCancelNotification.setBuffer( buf );
				fixCancelNotification.getAll();
				if (!validator.validate(fixCancelNotification)) return;
				l.onFixCancelNotification(fixCancelNotification);
				break;
			case MsgTypes.ENTRYNOTIFICATIONTOALLEGEDFIRM_INT:
				fixEntryNotificationtoAllegedFirm.setBuffer( buf );
				fixEntryNotificationtoAllegedFirm.getAll();
				if (!validator.validate(fixEntryNotificationtoAllegedFirm)) return;
				l.onFixEntryNotificationtoAllegedFirm(fixEntryNotificationtoAllegedFirm);
				break;
			case MsgTypes.EXECUTIONREPORTFILL_INT:
				fixExecutionReportFill.setBuffer( buf );
				fixExecutionReportFill.getAll();
				if (!validator.validate(fixExecutionReportFill)) return;
				l.onFixExecutionReportFill(fixExecutionReportFill);
				break;
			case MsgTypes.EXECUTIONRESTATEMENT_INT:
				fixExecutionRestatement.setBuffer( buf );
				fixExecutionRestatement.getAll();
				if (!validator.validate(fixExecutionRestatement)) return;
				l.onFixExecutionRestatement(fixExecutionRestatement);
				break;
			case MsgTypes.LOCKEDINNOTIFICATION_INT:
				fixLockedinNotification.setBuffer( buf );
				fixLockedinNotification.getAll();
				if (!validator.validate(fixLockedinNotification)) return;
				l.onFixLockedinNotification(fixLockedinNotification);
				break;
			case MsgTypes.LOCKEDINTRADEBREAK_INT:
				fixLockedinTradeBreak.setBuffer( buf );
				fixLockedinTradeBreak.getAll();
				if (!validator.validate(fixLockedinTradeBreak)) return;
				l.onFixLockedinTradeBreak(fixLockedinTradeBreak);
				break;
			case MsgTypes.ORDERACKNOWLEDGEMENT_INT:
				fixOrderAcknowledgement.setBuffer( buf );
				fixOrderAcknowledgement.getAll();
				if (!validator.validate(fixOrderAcknowledgement)) return;
				l.onFixOrderAcknowledgement(fixOrderAcknowledgement);
				break;
			case MsgTypes.ORDERREJECT_INT:
				fixOrderReject.setBuffer( buf );
				fixOrderReject.getAll();
				if (!validator.validate(fixOrderReject)) return;
				l.onFixOrderReject(fixOrderReject);
				break;
			case MsgTypes.PENDINGCANCEL_INT:
				fixPendingCancel.setBuffer( buf );
				fixPendingCancel.getAll();
				if (!validator.validate(fixPendingCancel)) return;
				l.onFixPendingCancel(fixPendingCancel);
				break;
			case MsgTypes.TRADEENTRYNOTIFICATIONTOENTERINGFIRM_INT:
				fixTradeEntryNotificationtoEnteringFirm.setBuffer( buf );
				fixTradeEntryNotificationtoEnteringFirm.getAll();
				if (!validator.validate(fixTradeEntryNotificationtoEnteringFirm)) return;
				l.onFixTradeEntryNotificationtoEnteringFirm(fixTradeEntryNotificationtoEnteringFirm);
				break;
			case MsgTypes.TRADEREPORTCANCEL_INT:
				fixTradeReportCancel.setBuffer( buf );
				fixTradeReportCancel.getAll();
				if (!validator.validate(fixTradeReportCancel)) return;
				l.onFixTradeReportCancel(fixTradeReportCancel);
				break;
			case MsgTypes.TRADEREPORTENTRY_INT:
				fixTradeReportEntry.setBuffer( buf );
				fixTradeReportEntry.getAll();
				if (!validator.validate(fixTradeReportEntry)) return;
				l.onFixTradeReportEntry(fixTradeReportEntry);
				break;
			case MsgTypes.HEARTBEAT_INT:
				fixHeartbeat.setBuffer( buf );
				fixHeartbeat.getAll();
				if (!validator.validate(fixHeartbeat)) return;
				l.onFixHeartbeat(fixHeartbeat);
				break;
			case MsgTypes.LOGON_INT:
				fixLogon.setBuffer( buf );
				fixLogon.getAll();
				if (!validator.validate(fixLogon)) return;
				l.onFixLogon(fixLogon);
				break;
			case MsgTypes.LOGOUT_INT:
				fixLogout.setBuffer( buf );
				fixLogout.getAll();
				if (!validator.validate(fixLogout)) return;
				l.onFixLogout(fixLogout);
				break;
			case MsgTypes.ORDERSINGLE_INT:
				fixOrderSingle.setBuffer( buf );
				fixOrderSingle.getAll();
				if (!validator.validate(fixOrderSingle)) return;
				l.onFixOrderSingle(fixOrderSingle);
				break;
			case MsgTypes.ORDERCANCELREJECT_INT:
				fixOrderCancelReject.setBuffer( buf );
				fixOrderCancelReject.getAll();
				if (!validator.validate(fixOrderCancelReject)) return;
				l.onFixOrderCancelReject(fixOrderCancelReject);
				break;
			case MsgTypes.REJECTEDCANCELREPLACE_INT:
				fixRejectedCancelReplace.setBuffer( buf );
				fixRejectedCancelReplace.getAll();
				if (!validator.validate(fixRejectedCancelReplace)) return;
				l.onFixRejectedCancelReplace(fixRejectedCancelReplace);
				break;
			case MsgTypes.ORDERCANCELREPLACEREQUEST_INT:
				fixOrderCancelReplaceRequest.setBuffer( buf );
				fixOrderCancelReplaceRequest.getAll();
				if (!validator.validate(fixOrderCancelReplaceRequest)) return;
				l.onFixOrderCancelReplaceRequest(fixOrderCancelReplaceRequest);
				break;
			case MsgTypes.ORDERCANCELREQUEST_INT:
				fixOrderCancelRequest.setBuffer( buf );
				fixOrderCancelRequest.getAll();
				if (!validator.validate(fixOrderCancelRequest)) return;
				l.onFixOrderCancelRequest(fixOrderCancelRequest);
				break;
			case MsgTypes.REJECT_INT:
				fixReject.setBuffer( buf );
				fixReject.getAll();
				if (!validator.validate(fixReject)) return;
				l.onFixReject(fixReject);
				break;
			case MsgTypes.RESENDREQUEST_INT:
				fixResendRequest.setBuffer( buf );
				fixResendRequest.getAll();
				if (!validator.validate(fixResendRequest)) return;
				l.onFixResendRequest(fixResendRequest);
				break;
			case MsgTypes.SEQUENCERESET_INT:
				fixSequenceReset.setBuffer( buf );
				fixSequenceReset.getAll();
				if (!validator.validate(fixSequenceReset)) return;
				l.onFixSequenceReset(fixSequenceReset);
				break;
			case MsgTypes.TESTREQUEST_INT:
				fixTestRequest.setBuffer( buf );
				fixTestRequest.getAll();
				if (!validator.validate(fixTestRequest)) return;
				l.onFixTestRequest(fixTestRequest);
				break;

			default:
				fixMessage.setBuffer(buf);
				fixMessage.getAll();
				FixUtils.findEndOfMessage(buf);
				if (!validator.validate(fixMessage)) return;
				l.onUnknownMessageType( fixMessage );
				break;

		}

	}

}
